name: integration

on:
  workflow_dispatch:

jobs:
  tool-check:
    container:
      image: rust:1:59
    steps:
      - run: cargo fmt -- --check
      - run: | 
        rustup component add clippy
        cargo clippy --locked --all-targets --features "strict"
      - run: cargo build --loocked --features "strict"
      - run: cargo test --locked
